"""
Genera productos_recetas_perfummua.sql
590 extractos × 3 presentaciones = 1770 productos
Categoría: RECETAS | Tipo: perfumes
Precios: 30ML=22,000 | 50ML=38,000 | 100ML=75,000 COP
Stock: 50 unidades por presentación
"""

EXTRACTOS = [
    "EXT-AFNAN-9 PM REBEL-UNI",
    "EXT-AFNAN-9 PM-MAS",
    "EXT-AHLI-CORVUS-FEM",
    "EXT-AHLI-KARPOS-UNI",
    "EXT-AHLI-PEGASUS-UNI",
    "EXT-AHLI-VEGA-UNI",
    "EXT-AL HARAMAIN AMBER OUD DUBAI NIGHT-MAS",
    "EXT-AL HARAMAIN-AMBER OUD AQUA DUBAI-UNI",
    "EXT-AL HARMAIN-AMBER OUD GOLD EDITION-UNI",
    "EXT-ANTONIO BANDERAS-BLUE SEDUCTION-MAS",
    "EXT-ARIANA GRANDE-ANGEL KISS-FEM",
    "EXT-ARIANA GRANDE-CLOUD PINK-FEM",
    "EXT-ARIANA GRANDE-CLOUD-FEM",
    "EXT-ARIANA GRANDE-SWEET LIKE CANDY-FEM",
    "EXT-ARIANA GRANDE-THANK U NEXT-FEM",
    "EXT-ARMAF-CLUB DE NUIT INTENSE-MAS",
    "EXT-ARMAF-CLUB DE NUIT MALEKA-FEM",
    "EXT-ARMAF-ISLAND BREEZE-FEM",
    "EXT-ARMAF-ODYSSEY CHOCOLAT-UNI",
    "EXT-ARMAF-ODYSSEY MANDARIN SKY-MAS",
    "EXT-ARMAF-YUM YUM-FEM",
    "EXT-AZZARO-AZZARO POUR HOMME-MAS",
    "EXT-BBW-CRAZY FOR YOU-FEM",
    "EXT-BHARARA-BHARARA BLEU-MAS",
    "EXT-BHARARA-BHARARA CHOCOLATE-UNI",
    "EXT-BHARARA-BHARARA KING-MAS",
    "EXT-BHARARA-BHARARA NICHE-UNI",
    "EXT-BHARARA-BHARARA ROSE-FEM",
    "EXT-BOND N9-BLEECKER STREET-UNI",
    "EXT-BRITNEY SPEARS-FANTASY-FEM",
    "EXT-BRITNEY SPEARS-MIDNIGHT FANTASY-FEM",
    "EXT-BURBERRY-BURBERRY HER-FEM",
    "EXT-BURBERRY-BURBERRY-FEM",
    "EXT-BVLGARI-AQVA MARINE-MAS",
    "EXT-BVLGARI-BLV-FEM",
    "EXT-BVLGARI-BVLGARI MAN IN BLACK-MAS",
    "EXT-BVLGARI-OMNIA CORAL-FEM",
    "EXT-BVLGARI-OMNIA CRYSTALLINE-FEM",
    "EXT-BVLGARI-OMNIA PINK SAPPHIRE-FEM",
    "EXT-CALVIN KLEIN-CK ONE-UNI",
    "EXT-CALVIN KLEIN-CKIN2U-FEM",
    "EXT-CAROLINA HERRERA-212 HEROES FOREVER-MAS",
    "EXT-CAROLINA HERRERA-212 HEROES-FEM",
    "EXT-CAROLINA HERRERA-212 SEXY-FEM",
    "EXT-CAROLINA HERRERA-212 VIP BLACK RED-MAS",
    "EXT-CAROLINA HERRERA-212 VIP BLACK-MAS",
    "EXT-CAROLINA HERRERA-212 VIP PARTY FEVER-MAS",
    "EXT-CAROLINA HERRERA-212 VIP ROSE RED-FEM",
    "EXT-CAROLINA HERRERA-212 VIP ROSE-FEM",
    "EXT-CAROLINA HERRERA-212 VIP-FEM",
    "EXT-CAROLINA HERRERA-212 VIP-MAS",
    "EXT-CAROLINA HERRERA-212-FEM",
    "EXT-CAROLINA HERRERA-212-MAS",
    "EXT-CAROLINA HERRERA-BAD BOY COBALT-MAS",
    "EXT-CAROLINA HERRERA-BAD BOY-MAS",
    "EXT-CAROLINA HERRERA-CAROLINA HERRERA-FEM",
    "EXT-CAROLINA HERRERA-CH-FEM",
    "EXT-CAROLINA HERRERA-CH-MAS",
    "EXT-CAROLINA HERRERA-GOOD GIRL BLUSH-FEM",
    "EXT-CAROLINA HERRERA-GOOD GIRL-FEM",
    "EXT-CAROLINA HERRERA-LA BOMBA-FEM",
    "EXT-CASAMORATI-BOUQUET IDEALE-FEM",
    "EXT-CHANEL-ALLURE SPORT-MAS",
    "EXT-CHANEL-BLEU DE CHANEL-MAS",
    "EXT-CHANEL-CHANCE EAU TENDRE-FEM",
    "EXT-CHANEL-CHANCE-FEM",
    "EXT-CHANEL-COCO MADEMOISELLE-FEM",
    "EXT-CHANEL-N5-FEM",
    "EXT-CHRISTIAN DIOR-DIOR HOMME INTENSE-MAS",
    "EXT-CHRISTIAN DIOR-FAHRENHEIT-MAS",
    "EXT-CHRISTIAN DIOR-JADORE-FEM",
    "EXT-CHRISTIAN DIOR-MISS DIOR BOUQUET-FEM",
    "EXT-CHRISTIAN DIOR-SAUVAGE ELIXIR-MAS",
    "EXT-CHRISTIAN DIOR-SAUVAGE-MAS",
    "EXT-CREED-AVENTUS HER-FEM",
    "EXT-CREED-AVENTUS-MAS",
    "EXT-CREED-QUEEN OF SILK-FEM",
    "EXT-CREED-SILVER MOUNTAIN WATER-MAS",
    "EXT-CRISTIANO RONALDO-CR7 ORIGINIS-MAS",
    "EXT-CRISTIANO RONALDO-LEGACY-MAS",
    "EXT-DIESEL-BAD INTENSE-MAS",
    "EXT-DIESEL-DIESEL PLUS PLUS-MAS",
    "EXT-DOLCE Y GABBANA-K-MAS",
    "EXT-DOLCE Y GABBANA-LIGHT BLUE-FEM",
    "EXT-DUMONT PARIS-NITRO ELIXIR-MAS",
    "EXT-DUMONT PARIS-NITRO RED-MAS",
    "EXT-ESCADA-AGUA DE SOL-FEM",
    "EXT-ESCADA-MIAMI BLOSSOM-FEM",
    "EXT-ESCADA-SORBETTO ROSSO-FEM",
    "EXT-ESCADA-TAJ SUNSET-FEM",
    "EXT-ESIKA-DORSAY-MAS",
    "EXT-FACONNABLE-FACONNABLE-MAS",
    "EXT-GIARDINI DI TOSCANA-BIANCO LATTE-UNI",
    "EXT-GILLES CANTUEL-ARSENAL-MAS",
    "EXT-GIORGIO ARMANI-ACQUA DI GIO PROFONDO-MAS",
    "EXT-GIORGIO ARMANI-ACQUA DI GIO-MAS",
    "EXT-GIORGIO ARMANI-STRONGER WITH YOU-MAS",
    "EXT-GIVENCHY-GIVENCHY BLUE-MAS",
    "EXT-GIVENCHY-GIVENCHY-MAS",
    "EXT-GUCCI-GUCCI GUILTY POUR HOMME-MAS",
    "EXT-HUGO BOSS-BOSS BOTTLED NIGHT-MAS",
    "EXT-HUGO BOSS-BOSS BOTTLED UNLIMITED-MAS",
    "EXT-HUGO BOSS-HUGO BOSS-MAS",
    "EXT-HUGO BOSS-HUGO RED-MAS",
    "EXT-ILMIN-IL FEMME-UNI",
    "EXT-ISSEY MIYAKE-ISSEY MIYAKE-FEM",
    "EXT-ISSEY MIYAKE-ISSEY MIYAKE-MAS",
    "EXT-JEAN PASCAL-JEAN PASCAL-MAS",
    "EXT-JEAN PAUL GAULTIER-DIVINE-FEM",
    "EXT-JEAN PAUL GAULTIER-JEAN PAUL GAULTIER LE MALE-MAS",
    "EXT-JEAN PAUL GAULTIER-LE BEAU-MAS",
    "EXT-JEAN PAUL GAULTIER-LE MALE ELIXIR-MAS",
    "EXT-JEAN PAUL GAULTIER-SCANDAL-FEM",
    "EXT-JEAN PAUL GAULTIER-SCANDAL-MAS",
    "EXT-JEAN PAUL GAULTIER-ULTRA MALE-MAS",
    "EXT-KAJAL-ALMAZ-UNI",
    "EXT-KAJAL-DAHAB-FEM",
    "EXT-KENZO-FLOWER BY KENZO-FEM",
    "EXT-KIM KARDASHIAN-BFF-FEM",
    "EXT-LACOSTE-LACOSTE BLANC-MAS",
    "EXT-LACOSTE-LACOSTE ESSENTIAL-MAS",
    "EXT-LACOSTE-LACOSTE NOIR-MAS",
    "EXT-LACOSTE-LACOSTE RED-MAS",
    "EXT-LACOSTE-LACOSTE WOMAN-FEM",
    "EXT-LACOSTE-TOUCH OF PINK-FEM",
    "EXT-LANCOME-LA VIDA ES BELLA FLORAL-FEM",
    "EXT-LANCOME-LA VIDA ES BELLA-FEM",
    "EXT-LATTAFA-AFEEF-UNI",
    "EXT-LATTAFA-AL NOBLE AMEER-UNI",
    "EXT-LATTAFA-AMETHYST-UNI",
    "EXT-LATTAFA-ART OF UNIVERSE-UNI",
    "EXT-LATTAFA-ASAD-MAS",
    "EXT-LATTAFA-ECLAIRE-FEM",
    "EXT-LATTAFA-EMEER-UNI",
    "EXT-LATTAFA-HAYA-FEM",
    "EXT-LATTAFA-HONOR Y GLORY-UNI",
    "EXT-LATTAFA-KHAMRAH DUKHAN-UNI",
    "EXT-LATTAFA-KHAMRAH-UNI",
    "EXT-LATTAFA-MALLOW MADNESS-FEM",
    "EXT-LATTAFA-MAYAR-FEM",
    "EXT-LATTAFA-NOBLE BLUSH-FEM",
    "EXT-LATTAFA-OUD FOR GLORY-UNI",
    "EXT-LATTAFA-QAED AL FURSAN-UNI",
    "EXT-LATTAFA-RAMZ SILVER-UNI",
    "EXT-LATTAFA-SHAHEEN GOLD-UNI",
    "EXT-LATTAFA-SUBLIME-UNI",
    "EXT-LATTAFA-VAINILLA FREAK-FEM",
    "EXT-LATTAFA-VICTORIA-UNI",
    "EXT-LATTAFA-YARA CANDY-FEM",
    "EXT-LATTAFA-YARA-FEM",
    "EXT-LE LABO-SANTAL 33-UNI",
    "EXT-LOEWE-SOLO-MAS",
    "EXT-LOLITA LEMPICKA-LOLITA LEMPICKA-FEM",
    "EXT-LORENZO PAZZAGLIA-SUMMER HAMMER-UNI",
    "EXT-LORENZO PAZZAGLIA-SUN GRIA-UNI",
    "EXT-LOUIS VOUITTON-IMAGINATION-MAS",
    "EXT-LOUIS VOUITTON-L\u00b4IMMENSITE-MAS",
    "EXT-LOUIS VOUITTON-OMBRE NOMADE-MAS",
    "EXT-MAISON CRIVELLI-OUD MARACUJA-UNI",
    "EXT-MAISON FRANCIS KURKDJIAN-BACCARAT ROUGE 540-UNI",
    "EXT-MANCERA-RED TOBACCO-UNI",
    "EXT-MARC JACOBS-DAISY LOVE-FEM",
    "EXT-MONTALE-ARABIANS TONKA-UNI",
    "EXT-MONTALE-NEPAL AOUD-FEM",
    "EXT-MONTALE-STARRY NIGHT-UNI",
    "EXT-MONTBLANC-STARWALKER-MAS",
    "EXT-MOSCHINO-MOSCHINO FOREVER-MAS",
    "EXT-MOSCHINO-TOY 2 BUBBLE GUM-FEM",
    "EXT-MOSCHINO-TOY 2 PEARL-UNI",
    "EXT-MOSCHINO-TOY 2-FEM",
    "EXT-MOSCHINO-TOY BOY-MAS",
    "EXT-NAUTICA-NAUTICA VOYAGE-MAS",
    "EXT-ORIENTICA-AMBER ROUGE-UNI",
    "EXT-ORIENTICA-VELVET GOLD-FEM",
    "EXT-OSCAR DE LA RENTA-OSCAR DE LA RENTA-MAS",
    "EXT-PACO RABANNE-1 MILLION ELIXIR-MAS",
    "EXT-PACO RABANNE-1 MILLION INTENSE-MAS",
    "EXT-PACO RABANNE-1 MILLION LUCKY-MAS",
    "EXT-PACO RABANNE-1 MILLION PRIVE-MAS",
    "EXT-PACO RABANNE-1 MILLION ROYAL-MAS",
    "EXT-PACO RABANNE-1 MILLION-MAS",
    "EXT-PACO RABANNE-BLACK XS AFRODISIACA-MAS",
    "EXT-PACO RABANNE-BLACK XS-MAS",
    "EXT-PACO RABANNE-FAME-FEM",
    "EXT-PACO RABANNE-INVICTUS INTENSE-MAS",
    "EXT-PACO RABANNE-INVICTUS LEGEND-MAS",
    "EXT-PACO RABANNE-INVICTUS VICTORY ABSOLU-MAS",
    "EXT-PACO RABANNE-INVICTUS VICTORY ELIXIR-MAS",
    "EXT-PACO RABANNE-INVICTUS VICTORY-MAS",
    "EXT-PACO RABANNE-INVICTUS-MAS",
    "EXT-PACO RABANNE-LADY MILLION GOLD-FEM",
    "EXT-PACO RABANNE-LADY MILLION-FEM",
    "EXT-PACO RABANNE-OLYMPEA-FEM",
    "EXT-PACO RABANNE-PHANTOM INTENSE-MAS",
    "EXT-PACO RABANNE-PURE XS-FEM",
    "EXT-PACO RABANNE-PURE XS-MAS",
    "EXT-PARFUMS DE MARLY-ALTHAIR-MAS",
    "EXT-PARFUMS DE MARLY-DELINA-FEM",
    "EXT-PARFUMS DE MARLY-KALAN-UNI",
    "EXT-PARFUMS DE MARLY-LAYTON-UNI",
    "EXT-PARIS HILTON-CAN CAN-FEM",
    "EXT-PARIS HILTON-DAZZLE-FEM",
    "EXT-PARIS HILTON-HEIRESS-FEM",
    "EXT-PARIS HILTON-PARIS HILTON-FEM",
    "EXT-PARIS HILTON-ROSE RUSH-FEM",
    "EXT-PERRY ELLIS-360 PURPLE-FEM",
    "EXT-PERRY ELLIS-360-FEM",
    "EXT-PERRY ELLIS-360-MAS",
    "EXT-PRADA-PARADOXE-FEM",
    "EXT-RALPH LAUREN-POLO BLUE-MAS",
    "EXT-RALPH LAUREN-POLO RED-MAS",
    "EXT-RALPH LAUREN-RALPH-FEM",
    "EXT-SABRINA CARPENTER-SWEET TOOTH-FEM",
    "EXT-SELENA GOMEZ-SELENA GOMEZ-FEM",
    "EXT-SHAKIRA-ELIXIR-FEM",
    "EXT-SOFIA VERGARA-SOFIA-FEM",
    "EXT-TED LAPIDUS-LAPIDUS POUR HOMME-MAS",
    "EXT-THIERRY MUGLER-ANGEL-FEM",
    "EXT-THIERRY MUGLER-ANGEL-MAS",
    "EXT-TOMMY HILFIGER-TOMMY GIRL-FEM",
    "EXT-TOMMY HILFIGER-TOMMY-MAS",
    "EXT-VALENTINO-DONNA BORN ROMA EXTRADOSE-FEM",
    "EXT-VALENTINO-DONNA CLASICA-FEM",
    "EXT-VALENTINO-UOMO BORN IN ROMA INTENSE-MAS",
    "EXT-VERSACE-BRIGHT CRYSTAL-FEM",
    "EXT-VERSACE-DYLAN PURPLE-FEM",
    "EXT-VERSACE-DYLAN TURQUOISE-FEM",
    "EXT-VERSACE-EROS ENERGY-MAS",
    "EXT-VERSACE-EROS-MAS",
    "EXT-VICTORIA SECRET-BOMBSHELL-FEM",
    "EXT-VICTORIA SECRET-COCONUT PASSION-FEM",
    "EXT-VICTORINOX-SWISS ARMY-MAS",
    "EXT-XERJOFF-ERBA PURA-UNI",
    "EXT-XERJOFF-NAXOS-UNI",
    "EXT-YANBAL-OHM-MAS",
    "EXT-YANBAL-SOLO-MAS",
    "EXT-YVES SAINT LAURENT-BABYCAT-FEM",
    "EXT-YVES SAINT LAURENT-BLACK OPIUM-FEM",
    "EXT-YVES SAINT LAURENT-Y-MAS",
    # --- Grupo 2 (sede Yamaha → sede-pm-2) ---
    "EXT-ACQUA DI PARMA-BERGAMOTTO DI CALABRIA-UNI",
    "EXT-AFNAN-9 PM-MAS",
    "EXT-AHLI-CORVUS-FEM",
    "EXT-AHLI-KARPOS-UNI",
    "EXT-AHLI-OVERDOSE-UNI",
    "EXT-AHLI-PEGASUS-UNI",
    "EXT-AHLI-VEGA-UNI",
    "EXT-AL HARAMAIN-AMBER OUD AQUA DUBAI-UNI",
    "EXT-AL HARAMAIN-AMBER OUD DUBAI NIGHT-UNI",
    "EXT-AL HARAMAIN-AMBER OUD GOLD EDITION-UNI",
    "EXT-AL HARAMAIN-AMBER OUD TOBACCO-UNI",
    "EXT-AL HARAMAIN-LAVENTURE BLANCHE-FEM",
    "EXT-AL HARAMAIN-MADINAH-UNI",
    "EXT-ANTONIO BANDERAS-BLUE SEDUCTION-MAS",
    "EXT-ARIANA GRANDE-ANGEL KISS-FEM",
    "EXT-ARIANA GRANDE-CLOUD PINK-FEM",
    "EXT-ARIANA GRANDE-CLOUD-FEM",
    "EXT-ARIANA GRANDE-MOD BLUSH-FEM",
    "EXT-ARIANA GRANDE-SWEET LIKE CANDY-FEM",
    "EXT-ARIANA GRANDE-THANK U NEXT-FEM",
    "EXT-ARMAF-CLUB DE NUIT INTENSE-MAS",
    "EXT-ARMAF-CLUB DE NUIT MALEKA-FEM",
    "EXT-ARMAF-CLUB DE NUIT SILLAGE-UNI",
    "EXT-ARMAF-ISLAND BREEZE-FEM",
    "EXT-ARMAF-ODYSSEY CHOCOLAT-UNI",
    "EXT-ARMAF-ODYSSEY MANDARIN SKY-MAS",
    "EXT-ARMAF-YUM YUM-FEM",
    "EXT-AVON-K VIDA FEM-FEM",
    "EXT-AZZARO-AZZARO POUR HOMME-MAS",
    "EXT-BBW-CRAZY FOR YOU-FEM",
    "EXT-BHARARA-BHARARA BLEU-MAS",
    "EXT-BHARARA-BHARARA KING-MAS",
    "EXT-BHARARA-BHARARA NICHE-UNI",
    "EXT-BOND N9-BLEECKER STREET-UN",
    "EXT-BRITNEY SPEARS-FANTASY-FEM",
    "EXT-BRITNEY SPEARS-MIDNIGHT FANTASY-FEM",
    "EXT-BURBERRY-BURBERRY HER-FEM",
    "EXT-BURBERRY-BURBERRY-FEM",
    "EXT-BVLGARI-AQVA MARINE-MAS",
    "EXT-BVLGARI-BLV-FEM",
    "EXT-BVLGARI-BVLGARI MAN IN BLACK-MAS",
    "EXT-BVLGARI-OMNIA CORAL-FEM",
    "EXT-BVLGARI-OMNIA CRYSTALLINE-FEM",
    "EXT-BVLGARI-OMNIA PINK SAPPHIRE-FEM",
    "EXT-CACHAREL-AMOR AMOR-FEM",
    "EXT-CALVIN KLEIN-CK ONE-UNI",
    "EXT-CALVIN KLEIN-CKIN2U-FEM",
    "EXT-CALVIN KLEIN-ESCAPE-FEM",
    "EXT-CALVIN KLEIN-ETERNITY-MAS",
    "EXT-CAROLINA HERRERA-212 HEROES FOREVER-MAS",
    "EXT-CAROLINA HERRERA-212 HEROES-FEM",
    "EXT-CAROLINA HERRERA-212 SEXY-FEM",
    "EXT-CAROLINA HERRERA-212 SEXY-MAS",
    "EXT-CAROLINA HERRERA-212 VIP BLACK EXTRA-MAS",
    "EXT-CAROLINA HERRERA-212 VIP BLACK RED-MAS",
    "EXT-CAROLINA HERRERA-212 VIP BLACK-MAS",
    "EXT-CAROLINA HERRERA-212 VIP PARTY FEVER-MAS",
    "EXT-CAROLINA HERRERA-212 VIP ROSE EXTRA-FEM",
    "EXT-CAROLINA HERRERA-212 VIP ROSE RED-FEM",
    "EXT-CAROLINA HERRERA-212 VIP ROSE-FEM",
    "EXT-CAROLINA HERRERA-212 VIP WILD PARTY-FEM",
    "EXT-CAROLINA HERRERA-212 VIP WINS-FEM",
    "EXT-CAROLINA HERRERA-212 VIP WINS-MAS",
    "EXT-CAROLINA HERRERA-212 VIP-FEM",
    "EXT-CAROLINA HERRERA-212 VIP-MAS",
    "EXT-CAROLINA HERRERA-212-FEM",
    "EXT-CAROLINA HERRERA-212-MAS",
    "EXT-CAROLINA HERRERA-BAD BOY COBALT-MAS",
    "EXT-CAROLINA HERRERA-BAD BOY-MAS",
    "EXT-CAROLINA HERRERA-CAROLINA HERRERA-FEM",
    "EXT-CAROLINA HERRERA-CAROLINA HERRERA-MAS",
    "EXT-CAROLINA HERRERA-CH BEAUTIES-FEM",
    "EXT-CAROLINA HERRERA-CH-FEM",
    "EXT-CAROLINA HERRERA-CH-MAS",
    "EXT-CAROLINA HERRERA-CHIC FOR MEN-MAS",
    "EXT-CAROLINA HERRERA-GOOD GIRL BLUSH-FEM",
    "EXT-CAROLINA HERRERA-GOOD GIRL-FEM",
    "EXT-CAROLINA HERRERA-LA BOMBA-FEM",
    "EXT-CAROLINA HERRERA-VERY GLAM-FEM",
    "EXT-CAROLINA HERRERA-VERY GOOD GIRL-FEM",
    "EXT-CARTIER-EAU DE CARTIER-UNI",
    "EXT-CASAMORATI-BOUQUET IDEALE-FEM",
    "EXT-CHANEL-ALLURE SPORT-MAS",
    "EXT-CHANEL-BLEU DE CHANEL-MAS",
    "EXT-CHANEL-CHANCE EAU TENDRE-FEM",
    "EXT-CHANEL-CHANCE-FEM",
    "EXT-CHANEL-COCO MADEMOISELLE-FEM",
    "EXT-CHANEL-N5-FEM",
    "EXT-CHRISTIAN DIOR-DIOR HOMME INTENSE-MAS",
    "EXT-CHRISTIAN DIOR-FAHRENHEIT-MAS",
    "EXT-CHRISTIAN DIOR-JADORE-FEM",
    "EXT-CHRISTIAN DIOR-MISS DIOR BOUQUET-FEM",
    "EXT-CHRISTIAN DIOR-SAUVAGE ELIXIR-MAS",
    "EXT-CHRISTIAN DIOR-SAUVAGE-MAS",
    "EXT-CREED-AVENTUS HER-FEM",
    "EXT-CREED-AVENTUS-MAS",
    "EXT-CREED-CARMINA-FEM",
    "EXT-CREED-GREEN IRISH TWEED-MAS",
    "EXT-CREED-QUEEN OF SILK-FEM",
    "EXT-CREED-SILVER MOUNTAIN WATER-MAS",
    "EXT-CRISTIANO RONALDO-CR7 ORIGINIS-MAS",
    "EXT-CRISTIANO RONALDO-LEGACY-MAS",
    "EXT-DIESEL-BAD INTENSE-MAS",
    "EXT-DIESEL-DIESEL PLUS PLUS-MAS",
    "EXT-DIESEL-FUEL FOR LIFE-MAS",
    "EXT-DIESEL-ONLY THE BRAVE-MAS",
    "EXT-DIESEL-SPIRIT OF THE BRAVE-MAS",
    "EXT-DOLCE Y GABBANA-DEVOTION-FEM",
    "EXT-DOLCE Y GABBANA-DOLCE Y GABBANA POUR HOMME-MAS",
    "EXT-DOLCE Y GABBANA-DOLCE Y GABBANA-FEM",
    "EXT-DOLCE Y GABBANA-K-MAS",
    "EXT-DOLCE Y GABBANA-LIGHT BLUE-FEM",
    "EXT-DOLCE Y GABBANA-PINEAPPLE-FEM",
    "EXT-DUMONT PARIS-NITRO ELIXIR-MAS",
    "EXT-DUMONT PARIS-NITRO RED-MAS",
    "EXT-ELIZABETH TAYLOR-DIAMANTES BLANCOS-FEM",
    "EXT-ENRIQUE IGLESIAS-ADRENALINE-MAS",
    "EXT-ESCADA-AGUA DE SOL-FEM",
    "EXT-ESCADA-BORN IN PARADISE-FEM",
    "EXT-ESCADA-CHERRY IN THE AIR-FEM",
    "EXT-ESCADA-FIESTA CARIOCA-FEM",
    "EXT-ESCADA-MIAMI BLOSSOM-FEM",
    "EXT-ESCADA-MOON SPARKLE-FEM",
    "EXT-ESCADA-SORBETTO ROSSO-FEM",
    "EXT-ESCADA-TAJ SUNSET-FEM",
    "EXT-ESIKA-DORSAY-MAS",
    "EXT-ESIKA-WINNER SPORT-MAS",
    "EXT-FACONNABLE-FACONNABLE-MAS",
    "EXT-FRED HAYMAN-273-FEM",
    "EXT-GIARDINI DI TOSCANA-BIANCO LATTE-UNI",
    "EXT-GILLES CANTUEL-ARSENAL-MAS",
    "EXT-GIORGIO ARMANI-ACQUA DI GIO ABSOLU-MAS",
    "EXT-GIORGIO ARMANI-ACQUA DI GIO PROFONDO-MAS",
    "EXT-GIORGIO ARMANI-ACQUA DI GIO-MAS",
    "EXT-GIORGIO ARMANI-STRONGER WITH YOU-MAS",
    "EXT-GIVENCHY-GIVENCHY BLUE-MAS",
    "EXT-GIVENCHY-GIVENCHY-MAS",
    "EXT-GIVENCHY-INTERDIT-FEM",
    "EXT-GIVENCHY-ORGANZA-FEM",
    "EXT-GUCCI- GUCCI GUILTY POUR HOMME-MAS",
    "EXT-GUESS-GUESS GIRL-FEM",
    "EXT-HUGO BOSS-BOSS BOTTLED NIGHT-MAS",
    "EXT-HUGO BOSS-BOSS BOTTLED UNLIMITED-MAS",
    "EXT-HUGO BOSS-BOSS IN MOTION-MAS",
    "EXT-HUGO BOSS-BOSS ORANGE-MAS",
    "EXT-HUGO BOSS-BOSS THE SCENT ABSOLUTE-MAS",
    "EXT-HUGO BOSS-HUGO BOSS-MAS",
    "EXT-HUGO BOSS-HUGO RED-MAS",
    "EXT-HUGO BOSS-THE SCENT PURE ACCORD-MAS",
    "EXT-HUGO BOSS-XX-FEM",
    "EXT-ILMIN-IL EGO-UNI",
    "EXT-ILMIN-IL FEMME-UNI",
    "EXT-ILMIN-IL KAKUNO-UNI",
    "EXT-INITIO-MUSK THERAPY-UNI",
    "EXT-ISSEY MIYAKE-ISSEY MIYAKE-FEM",
    "EXT-ISSEY MIYAKE-ISSEY MIYAKE-MAS",
    "EXT-JEAN PASCAL-JEAN PASCAL-MAS",
    "EXT-JEAN PAUL GAULTIER-DIVINE-FEM",
    "EXT-JEAN PAUL GAULTIER-JEAN PAUL GAULTIER LE MALE-MAS",
    "EXT-JEAN PAUL GAULTIER-JEAN PAUL GAULTIER-FEM",
    "EXT-JEAN PAUL GAULTIER-LE BEAU-MAS",
    "EXT-JEAN PAUL GAULTIER-LE MALE ELIXIR-MAS",
    "EXT-JEAN PAUL GAULTIER-SCANDAL-FEM",
    "EXT-JEAN PAUL GAULTIER-SCANDAL-MAS",
    "EXT-JEAN PAUL GAULTIER-ULTRA MALE-MAS",
    "EXT-JESUS DEL POZO-HALLOWEEN-MAS",
    "EXT-KAJAL-ALMAZ-UNI",
    "EXT-KATY PERRY-MEOW-FEM",
    "EXT-KENZO-FLOWER BY KENZO-FEM",
    "EXT-KILLIAN-ROLLING IN LOVE-UNI",
    "EXT-KIM KARDASHIAN-BFF-FEM",
    "EXT-LACOSTE-LACOSTE BLANC-MAS",
    "EXT-LACOSTE-LACOSTE ESSENTIAL-MAS",
    "EXT-LACOSTE-LACOSTE MAGNETIC-FEM",
    "EXT-LACOSTE-LACOSTE NOIR-MAS",
    "EXT-LACOSTE-LACOSTE RED-MAS",
    "EXT-LACOSTE-LACOSTE WOMAN-FEM",
    "EXT-LACOSTE-SPARKLING-FEM",
    "EXT-LACOSTE-TOUCH OF PINK-FEM",
    "EXT-LANCOME-LA VIDA ES BELLA FLORAL-FEM",
    "EXT-LANCOME-LA VIDA ES BELLA-FEM",
    "EXT-LATTAFA-AFEEF-UNI",
    "EXT-LATTAFA-AL NOBLE AMEER-UNI",
    "EXT-LATTAFA-AMEER AL OUDH INTENSE-UNI",
    "EXT-LATTAFA-AMETHYST-UNI",
    "EXT-LATTAFA-ART OF UNIVERSE-UNI",
    "EXT-LATTAFA-ASAD-MAS",
    "EXT-LATTAFA-ECLAIRE-FEM",
    "EXT-LATTAFA-EMEER-UNI",
    "EXT-LATTAFA-HAYA-FEM",
    "EXT-LATTAFA-HER CONFESSION-FEM",
    "EXT-LATTAFA-HONOR Y GLORY-UNI",
    "EXT-LATTAFA-KHAMRAH DUKHAN-UNI",
    "EXT-LATTAFA-KHAMRAH-UNI",
    "EXT-LATTAFA-MALLOW MADNESS-FEM",
    "EXT-LATTAFA-MAYAR CHERRY INTENSE-UNI",
    "EXT-LATTAFA-MAYAR-FEM",
    "EXT-LATTAFA-NOBLE BLUSH-FEM",
    "EXT-LATTAFA-OUD FOR GLORY-UNI",
    "EXT-LATTAFA-QAED AL FURSAN-UNI",
    "EXT-LATTAFA-RAMZ SILVER-UNI",
    "EXT-LATTAFA-SEHR-UNI",
    "EXT-LATTAFA-SHAHEEN GOLD-UNI",
    "EXT-LATTAFA-SUBLIME-UNI",
    "EXT-LATTAFA-TERIAQ INTENSE-UNI",
    "EXT-LATTAFA-VAINILLA FREAK-FEM",
    "EXT-LATTAFA-YARA CANDY-FEM",
    "EXT-LATTAFA-YARA-FEM",
    "EXT-LE LABO-MATCHA 26-UNI",
    "EXT-LE LABO-SANTAL 33-UNI",
    "EXT-LOEWE-LOEWE 7-MAS",
    "EXT-LOEWE-SOLO-MAS",
    "EXT-LOLITA LEMPICKA-LOLITA LEMPICKA-FEM",
    "EXT-LORENZO PAZZAGLIA-SUMMER HAMMER-UNI",
    "EXT-LORENZO PAZZAGLIA-SUN GRIA-UNI",
    "EXT-LOUIS VOUITTON-ATTRAPE REVES-FEM",
    "EXT-LOUIS VOUITTON-L\u00b4IMMENSITE-MAS",
    "EXT-LOUIS VOUITTON-OMBRE NOMADE-MAS",
    "EXT-MAISON CRIVELLI-OUD MARACUJA-UNI",
    "EXT-MAISON FRANCIS KURKDJIAN-BACCARAT ROUGE 540-UNI",
    "EXT-MANCERA-INSTANT CRUSH-UNI",
    "EXT-MANCERA-JARDIN EXCLUSIF-UNI",
    "EXT-MANCERA-RED TOBACCO-UNI",
    "EXT-MANCERA-SILVER BLUE-UNI",
    "EXT-MARC JACOBS-DAISY LOVE-FEM",
    "EXT-MERCEDEZ BENZ- MERCEDEZ BENZ IN RED-FEM",
    "EXT-MONTALE-ARABIANS TONKA-UNI",
    "EXT-MONTALE-INTENSE CAFE-UNI",
    "EXT-MONTALE-NEPAL AOUD-FEM",
    "EXT-MONTALE-STARRY NIGHT-UNI",
    "EXT-MONTBLANC-EXPLORER-MAS",
    "EXT-MONTBLANC-LEGEND RED-MAS",
    "EXT-MONTBLANC-LEGEND-MAS",
    "EXT-MONTBLANC-STARWALKER-MAS",
    "EXT-MOSCHINO-FUNNY-FEM",
    "EXT-MOSCHINO-MOSCHINO FOREVER-MAS",
    "EXT-MOSCHINO-TOY 2 BUBBLE GUM-FEM",
    "EXT-MOSCHINO-TOY 2 PEARL-UNI",
    "EXT-MOSCHINO-TOY 2-FEM",
    "EXT-MOSCHINO-TOY BOY-MAS",
    "EXT-NAUTICA-NAUTICA VOYAGE-MAS",
    "EXT-NINNA RICCI-LES MONSTRES DE NINA RICCI LUNA-FEM",
    "EXT-NI\u00d1OS-ARRURU-UNI",
    "EXT-NI\u00d1OS-COOL BOY-MAS",
    "EXT-NI\u00d1OS-DOLLY GIRL-FEM",
    "EXT-NI\u00d1OS-GALAXY-MAS",
    "EXT-NI\u00d1OS-MIMITOS-MAS",
    "EXT-NI\u00d1OS-PRETTY IN PINK-FEM",
    "EXT-NI\u00d1OS-SWEET CREAM-FEM",
    "EXT-ORIENTICA-AMBER ROUGE-UNI",
    "EXT-ORIENTICA-AZURE FANTASY-UNI",
    "EXT-ORIENTICA-OUD SAFFRON-UNI",
    "EXT-ORIENTICA-VELVET GOLD-FEM",
    "EXT-OSCAR DE LA RENTA-OSCAR DE LA RENTA-MAS",
    "EXT-PACO RABANNE-1 MILLION ELIXIR-MAS",
    "EXT-PACO RABANNE-1 MILLION INTENSE-MAS",
    "EXT-PACO RABANNE-1 MILLION LUCKY-MAS",
    "EXT-PACO RABANNE-1 MILLION PRIVE-MAS",
    "EXT-PACO RABANNE-1 MILLION ROYAL-MAS",
    "EXT-PACO RABANNE-1 MILLION-MAS",
    "EXT-PACO RABANNE-BLACK XS AFRODISIACA-MAS",
    "EXT-PACO RABANNE-BLACK XS BE LEGEND-MAS",
    "EXT-PACO RABANNE-BLACK XS L`EXCES-MAS",
    "EXT-PACO RABANNE-BLACK XS POTION-FEM",
    "EXT-PACO RABANNE-BLACK XS POTION-MAS",
    "EXT-PACO RABANNE-BLACK XS-MAS",
    "EXT-PACO RABANNE-FAME-FEM",
    "EXT-PACO RABANNE-INVICTUS INTENSE-MAS",
    "EXT-PACO RABANNE-INVICTUS LEGEND-MAS",
    "EXT-PACO RABANNE-INVICTUS VICTORY ELIXIR-MAS",
    "EXT-PACO RABANNE-INVICTUS VICTORY-MAS",
    "EXT-PACO RABANNE-INVICTUS-MAS",
    "EXT-PACO RABANNE-LADY MILLION GOLD-FEM",
    "EXT-PACO RABANNE-LADY MILLION LUCKY-FEM",
    "EXT-PACO RABANNE-LADY MILLION-FEM",
    "EXT-PACO RABANNE-OLYMPEA-FEM",
    "EXT-PACO RABANNE-PHANTOM INTENSE-MAS",
    "EXT-PACO RABANNE-PHANTOM LEGION-MAS",
    "EXT-PACO RABANNE-PHANTOM-MAS",
    "EXT-PACO RABANNE-PURE XS NIGHT-MAS",
    "EXT-PACO RABANNE-PURE XS-FEM",
    "EXT-PACO RABANNE-PURE XS-MAS",
    "EXT-PARFUMS DE MARLY-ALTHAIR-MAS",
    "EXT-PARFUMS DE MARLY-DELINA-FEM",
    "EXT-PARFUMS DE MARLY-KALAN-UNI",
    "EXT-PARFUMS DE MARLY-LAYTON-UNI",
    "EXT-PARFUMS DE MARLY-PEGASUS-UNI",
    "EXT-PARFUMS DE MARLY-SEDLEY-UNI",
    "EXT-PARIS HILTON-CAN CAN-FEM",
    "EXT-PARIS HILTON-DAZZLE-FEM",
    "EXT-PARIS HILTON-HEIRESS-FEM",
    "EXT-PARIS HILTON-PARIS HILTON-FEM",
    "EXT-PARIS HILTON-PARIS HILTON-MAS",
    "EXT-PARIS HILTON-PASSPORT IN PARIS-FEM",
    "EXT-PARIS HILTON-ROSE RUSH-FEM",
    "EXT-PERRY ELLIS-360 CORAL-FEM",
    "EXT-PERRY ELLIS-360 PURPLE-FEM",
    "EXT-PERRY ELLIS-360 RED-MAS",
    "EXT-PERRY ELLIS-360-FEM",
    "EXT-PERRY ELLIS-360-MAS",
    "EXT-PRADA-PARADOXE-FEM",
    "EXT-RALPH LAUREN-POLO BLUE-MAS",
    "EXT-RALPH LAUREN-POLO RED-MAS",
    "EXT-RALPH LAUREN-RALPH CLUB-MAS",
    "EXT-RALPH LAUREN-RALPH-FEM",
    "EXT-REYANE TRADITION-INSURRECTION-MAS",
    "EXT-RIHANNA-KISS-FEM",
    "EXT-ROGER GALLET-MARIA FARINA-MAS",
    "EXT-SABRINA CARPENTER-SWEET TOOTH-FEM",
    "EXT-SELENA GOMEZ-SELENA GOMEZ-FEM",
    "EXT-SHAKIRA-ELIXIR-FEM",
    "EXT-SHAKIRA-ROCK-FEM",
    "EXT-SOFIA VERGARA-SOFIA-FEM",
    "EXT-SOL DE JANEIRO-CHEIROSA 68-FEM",
    "EXT-TED LAPIDUS-LAPIDUS POUR HOMME-MAS",
    "EXT-THIERRY MUGLER-ANGEL NOVA-FEM",
    "EXT-THIERRY MUGLER-ANGEL-FEM",
    "EXT-THIERRY MUGLER-ANGEL-MAS",
    "EXT-TIZIANA TERENZI-KIRKE-UNI",
    "EXT-TOMMY HILFIGER-TOMMY GIRL-FEM",
    "EXT-TOMMY HILFIGER-TOMMY-MAS",
    "EXT-VALENTINO-DONNA BORN IN ROMA-FEM",
    "EXT-VALENTINO-DONNA BORN ROMA EXTRADOSE-FEM",
    "EXT-VALENTINO-UOMO BORN IN ROMA INTENSE-MAS",
    "EXT-VALENTINO-VALENTINO UOMO-MAS",
    "EXT-VERSACE-BRIGHT CRYSTAL-FEM",
    "EXT-VERSACE-DYLAN PURPLE-FEM",
    "EXT-VERSACE-DYLAN TURQUOISE-FEM",
    "EXT-VERSACE-EAU FRAICHE-MAS",
    "EXT-VERSACE-EROS ENERGY-MAS",
    "EXT-VERSACE-EROS FLAME-MAS",
    "EXT-VERSACE-EROS-MAS",
    "EXT-VICTORIA SECRET-BOMBSHELL-FEM",
    "EXT-VICTORIA SECRET-COCONUT PASSION-FEM",
    "EXT-VICTORIA SECRET-JUICED BERRY-FEM",
    "EXT-VICTORIA SECRET-VAINILLA-FEM",
    "EXT-VICTORINOX-SWISS ARMY-MAS",
    "EXT-XERJOFF-ERBA PURA-UNI",
    "EXT-YANBAL-CCORI ROSE-FEM",
    "EXT-YANBAL-CELOS-FEM",
    "EXT-YANBAL-CIELO-FEM",
    "EXT-YANBAL-GAIA-FEM",
    "EXT-YANBAL-OHM-MAS",
    "EXT-YANBAL-OSADIA-FEM",
    "EXT-YANBAL-OSADIA-MAS",
    "EXT-YANBAL-SOLO-MAS",
    "EXT-YANBAL-TEMPTATION-FEM",
    "EXT-YANBAL-TEMPTATION-MAS",
    "EXT-YVES SAINT LAURENT-BABYCAT-FEM",
    "EXT-YVES SAINT LAURENT-BLACK OPIUM-FEM",
    "EXT-YVES SAINT LAURENT-Y-MAS",
]

# Primeros 239 = sede Banco Agrario (sede-pm-1), siguientes 351 = sede Yamaha (sede-pm-2)
_G1 = 239
SEDES_PER_ITEM = ["sede-pm-1"] * _G1 + ["sede-pm-2"] * (len(EXTRACTOS) - _G1)

GENEROS = {"-MAS", "-FEM", "-UNI", "-UN"}

def clean_name(articulo: str) -> str:
    """
    Extrae el nombre limpio del código de extracto.
    EXT-BRAND-NAME-GENDER  → NAME
    EXT-BRAND NAME COMBINED-GENDER → BRAND NAME COMBINED  (sin separador de marca)
    """
    # Quitar prefijo EXT-
    s = articulo.removeprefix("EXT-")
    # Quitar sufijo de género
    for g in GENEROS:
        if s.endswith(g):
            s = s[: -len(g)]
            break
    # Quitar la marca (todo hasta el primer guión, si existe)
    idx = s.find("-")
    if idx != -1:
        s = s[idx + 1:]
    return s.strip()


def sql_escape(s: str) -> str:
    """Escapa comillas simples para SQL."""
    return s.replace("'", "\\'")


TENANT_ID = "d46bec36-5259-4b5b-83c7-01f1e6ea5dcd"
ENTRY_DATE = "2026-03-23"
SIZES = [
    (30,  22000),
    (50,  38000),
    (100, 75000),
]
BATCH_SIZE = 200  # filas por INSERT


def generate_sql(output_path: str, dedup: bool = False):
    items = list(zip(EXTRACTOS, SEDES_PER_ITEM))
    if dedup:
        seen_art: set = set()
        filtered = []
        for art, sede in items:
            k = art.strip()
            if k not in seen_art:
                seen_art.add(k)
                filtered.append((k, sede))
        items = filtered
    else:
        items = [(a.strip(), s) for a, s in items]
    total = len(items)
    print(f"Extractos únicos: {total}")
    print(f"Productos a generar: {total * 3}")

    header = f"""\
-- ============================================================
-- PRODUCTOS RECETAS: {total} extractos × 3 presentaciones = {total * 3} productos
-- Tenant: {TENANT_ID} (Perfum Mua)
-- Categoría: RECETAS | Tipo: perfumes
-- Precios: 30ML=22,000 | 50ML=38,000 | 100ML=75,000 COP
-- Stock inicial: 50 unidades por presentación
-- Ejecutar: mysql -u root -p stockpro_db < productos_recetas_perfummua.sql
-- ============================================================

USE stockpro_db;

SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
SET @tid = '{TENANT_ID}' COLLATE utf8mb4_unicode_ci;

-- ============================================================
-- 1. CATEGORÍA RECETAS
-- ============================================================
INSERT IGNORE INTO categories (id, tenant_id, name, description)
VALUES ('RECETAS', @tid, 'recetas', 'Perfumes terminados por presentacion: 30ML, 50ML, 100ML');

-- ============================================================
-- 2. LIMPIAR PRODUCTOS RECETAS PREVIOS (idempotente)
-- ============================================================
DELETE FROM products WHERE tenant_id = @tid AND id LIKE 'REC-%';

-- ============================================================
-- 3. INSERTAR {total * 3} PRODUCTOS
-- ============================================================
"""

    # Generar todas las filas
    rows = []
    for n, (articulo, sede_id) in enumerate(items, start=1):
        nombre_limpio = clean_name(articulo)
        art_esc = sql_escape(articulo)
        for ml, precio in SIZES:
            prod_id   = f"REC-{n}-{ml}"
            sku       = f"PM-REC-{n}-{ml}ML"
            name_val  = sql_escape(f"{nombre_limpio} {ml}ML")
            rows.append(
                f"('{prod_id}', @tid, '{name_val}', '{art_esc}', "
                f"'RECETAS', 'perfumes', '{sku}', "
                f"50, 5, '{ENTRY_DATE}', 0, {precio}, {ml}, 'ml', '{sede_id}')"
            )

    # Escribir en batches
    col_list = (
        "INSERT INTO products\n"
        "(id, tenant_id, name, articulo, category, product_type, sku,\n"
        " stock, reorder_point, entry_date, purchase_price, sale_price,\n"
        " net_weight, weight_unit, sede_id)\nVALUES\n"
    )
    footer = "\nSET FOREIGN_KEY_CHECKS = 1;\nSET UNIQUE_CHECKS = 1;\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        batch_num = 0
        for start in range(0, len(rows), BATCH_SIZE):
            batch = rows[start : start + BATCH_SIZE]
            batch_num += 1
            f.write(col_list)
            f.write(",\n".join(batch))
            f.write(";\n\n")
        f.write(footer)

    print(f"Archivo generado: {output_path}")
    print(f"Batches INSERT: {batch_num}")
    print(f"Total filas: {len(rows)}")


if __name__ == "__main__":
    import os
    base = os.path.dirname(__file__)

    out_full = os.path.join(base, "productos_recetas_perfummua.sql")
    generate_sql(out_full, dedup=False)

    out_dedup = os.path.join(base, "productos_recetas_sin_duplicados.sql")
    generate_sql(out_dedup, dedup=True)
